[package]
name = "machelix_bridge"
version = "0.1.0"
edition = "2021"
authors = ["MacHelix Contributors"]
description = "Bridge between Helix and MacVim"

[dependencies]
libc = "0.2"

[lib]
name = "machelix_bridge"
crate-type = ["staticlib", "cdylib"]